# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(default='About this product')),
                ('short_desc', models.CharField(default='Shortened product description', max_length=250)),
                ('stock', models.IntegerField(default=0)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(default='image/default.jpg', upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
    ]
