# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField()),
                ('name', models.TextField()),
                ('date_initial', models.DateTimeField()),
                ('date_final', models.DateTimeField()),
                ('about', models.TextField()),
                ('tutor', models.TextField()),
                ('max_participants', models.IntegerField()),
                ('height_field', models.IntegerField(default=200)),
                ('width_field', models.IntegerField(default=300)),
                ('type', models.TextField()),
                ('validated', models.BooleanField(default=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, height_field=b'height_field1', upload_to=b'events', width_field=b'width_field1')),
                ('image2', models.ImageField(blank=True, height_field=b'height_field2', upload_to=b'events', width_field=b'width_field2')),
                ('image3', models.ImageField(blank=True, height_field=b'height_field3', upload_to=b'events', width_field=b'width_field3')),
                ('height_field1', models.IntegerField(default=200)),
                ('width_field1', models.IntegerField(default=300)),
                ('height_field2', models.IntegerField(default=200)),
                ('width_field2', models.IntegerField(default=300)),
                ('height_field3', models.IntegerField(default=200)),
                ('width_field3', models.IntegerField(default=300)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TutorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorName', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventImages'),
        ),
    ]
