# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='image1',
            field=models.ImageField(blank=True, height_field='height_field1', upload_to='events', width_field='width_field1'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image2',
            field=models.ImageField(blank=True, height_field='height_field2', upload_to='events', width_field='width_field2'),
        ),
        migrations.AlterField(
            model_name='eventimages',
            name='image3',
            field=models.ImageField(blank=True, height_field='height_field3', upload_to='events', width_field='width_field3'),
        ),
    ]
