# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='card_exp_month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_exp_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='card_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='charge_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cvc',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
