# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20171220_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='card_number',
            field=models.BigIntegerField(default=1),
        ),
    ]
