# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselIMGs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.CharField(default=b'media/index_carousel/1.png', max_length=500)),
                ('img2', models.CharField(default=b'media/index_carousel/2.png', max_length=500)),
                ('img3', models.CharField(default=b'media/index_carousel/3.png', max_length=500)),
                ('img4', models.CharField(default=b'media/index_carousel/4.png', max_length=500)),
                ('img5', models.CharField(default=b'media/index_carousel/5.png', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EmailsBanidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudoEntrevista', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
