# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 18:02

from __future__ import unicode_literals

import WebSite.utilizadores.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phoneNumber', models.CharField(blank=True, max_length=16)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('picUrl', models.CharField(default='media/userPics/user.png', max_length=500)),
                ('type', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('reprovado', models.BooleanField(default=False)),
                ('bio', models.TextField(default='')),
                ('videoUrl', models.CharField(blank=True, default='', max_length=500)),
                ('categorias', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', WebSite.utilizadores.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254)),
                ('imgUrl', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PropostaRegisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(default='', max_length=1000)),
                ('imgUrl', models.CharField(default=None, max_length=500)),
                ('videoUrl', models.CharField(blank=True, default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Artesao',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('geolocation', models.CharField(default='', max_length=500)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('propostaRegisto', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilizadores.PropostaRegisto')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilizadores.baseuser',),
        ),
        migrations.CreateModel(
            name='Criativo',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('geolocation', models.CharField(default='', max_length=500)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('propostaRegisto', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilizadores.PropostaRegisto')),
            ],
            options={
                'abstract': False,
            },
            bases=('utilizadores.baseuser',),
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adress', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('utilizadores.baseuser',),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
