# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0003_remove_baseuser_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artesao',
            name='cidade',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='criativo',
            name='cidade',
            field=models.CharField(default='', max_length=200),
        ),
    ]
